repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: file-contents-sorter
      - id: forbid-submodules
      - id: name-tests-test
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.5.5
    hooks:
      - id: ruff
        args:
          - '--fix'
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        additional_dependencies: [ "bandit[toml]" ]
