[tool.ruff]
fix-only = true
lint.select = ["ANN", "B", "DJ", "E", "F", "I", "N", "UP"]

[tool.bandit]
skips = ["B104"]
exclude_dirs = [".secrets/", ".venv/", "logs", "docs"]

[tool.bandit.assert_used]
skips = ['*_test.py']
